In [2]:
import numpy as np
def evals(A, B):
  return np.linalg.eigvalsh(A + B)

A = np.array([[3, 4], [4, 3]])
B = np.array([[6, 0], [0, 6]])

print(A)
print(B)
print(A+B)
print(evals(A, B))
sum_eigenvalues = evals(A, B)[0] + evals(A, B)[1]

assert type(A) == np.ndarray
assert type(B) == np.ndarray
assert type(A+B) == np.ndarray
assert type(evals(A, B)) == np.ndarray
assert np.allclose(sum_eigenvalues, 18)

[[3 4]
 [4 3]]
[[6 0]
 [0 6]]
[[9 4]
 [4 9]]
[ 5. 13.]
